### PR TITLE
[WIP] Benchmark for class name determination

### PR DESCRIPTION
**Pull request by oqq**
This PR provides a benchmark for the `AggregateRoot::determineEventHandlerMethodFor()` method.
Without challenging the current implementation, this benchmark could has affects in future implementations, since we are currently not using the best performant way.

### CODE REVIEW

**Comment by sandrokeil** [comment]
I would prefer the `@Subject` Annotation, so we can get rid off the `bench` Prefix on function names. This looks better in the report. The `@group` Annotation could be useful to for further benchmarks.

**Comment by prolic** [comment]
I don't think benchmarks for decision making should be in this repository. Maybe we can create a new repo "various-benchmarks" where we can collect something like this.

Thoughts? /cc @codeliner

**Comment by oqq** [comment]
@prolic i share this opinion. On working on this pr i have found out it makes more sense to provide only benchmarks for adapters, as an assistance to choice one.

But providing this benchmark could help to explain in the future why we have implemented parts in a special way but not in an other one. A "benchmarks" repository for that would be fine!

@sandrokeil i am full with you to using ```@Subject```. Already implemented in my local fork. :)
Will not push it until a decision for the right repository is made.

**Comment by prolic** [comment]
@oqq https://github.com/prooph/various-benchmarks

**Pull request closed without merging**
