### PR TITLE
PHP8 compability

### PR DESCRIPTION
**Pull request by fritz-gerneth**

### CODE REVIEW

**Comment by fritz-gerneth** [comment]
This is now ready :)

**Comment by prolic** [comment]
Thanks man!

**Comment by prolic** [comment]
https://github.com/prooph/event-sourcing/releases/tag/v5.7.0

**Comment by basz** [comment]
just noticed that the tag and release name do not match

**Comment by prolic** [comment]
> just noticed that the tag and release name do not match

ups, fixed, thanks

**Pull request merged**
