### PR TITLE
Allow basic event store interface in repository

### PR DESCRIPTION
**Pull request by codeliner**
We can allow any event store implementing the basic event store interface. If event store does not trigger action events the user has to call `AggregateRepository::saveAggregate` instead.

### CODE REVIEW

**Comment by prolic** [comment]
I think we should remove the commit listener and always call saveAggregate then. You cannot switch the event store implementation otherwise, because your repository is bound to the used event store implementation.

**Comment by codeliner** [comment]
I guess decreased coverage can be ignored. It is only a side effect due to less loc

**Comment by codeliner** [comment]
@prolic what about the identity map. When should it be cleared then?

**Comment by codeliner** [comment]
Should we remove the aggregate from identity map when `saveAggregate` is called?

**Comment by prolic** [comment]
This means in all command handlers you need to remove or add save aggregate method when you switch the event store implementation. Especially the flywheel es is meant to be used for development and cannot exchange the postgres es. So remove the commit listener and always call saveAggregate is much safer.

**Comment by prolic** [comment]
Ah yes, saveAggregate should remove from identity map.

**Comment by codeliner** [comment]
k, I'll update the PR

**Comment by codeliner** [comment]
done @prolic 

decreased coverage still caused by less loc

**Pull request merged**
