### PR TITLE
require aggregate changed to have non empty ar id

### PR DESCRIPTION
**Pull request by prolic**
resolves https://github.com/prooph/event-sourcing/issues/83

ping @enumag - does that work for you?

### CODE REVIEW

**Comment by enumag** [comment]
Not really because my events often override the aggregateId method to return one of the properties. In the case I reported it was a wrong property. This wouldn't have helped with that particular case.

**Comment by prolic** [comment]
Then maybe change the getter as well?

Sascha-Oliver Prolic


Am Sa., 3. Nov. 2018 um 05:12 Uhr schrieb Jáchym Toušek <
notifications@github.com>:

**Comment by enumag** [comment]
A bug in the getter was what caused the event to be commited without aggregateId. Anyway it's not too important. I think you can just close it.

**Comment by prolic** [comment]
Okay, thanks for your input.

**Pull request closed without merging**
